# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EdFiStudentGradebookEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'gradebook_entry_reference': 'EdFiGradebookEntryReference',
        'student_reference': 'EdFiStudentReference',
        'assignment_late_status_descriptor': 'str',
        'competency_level_descriptor': 'str',
        'date_fulfilled': 'date',
        'diagnostic_statement': 'str',
        'letter_grade_earned': 'str',
        'numeric_grade_earned': 'float',
        'points_earned': 'float',
        'submission_status_descriptor': 'str',
        'time_fulfilled': 'str',
        'etag': 'str'
    }

    attribute_map = {
        'id': 'id',
        'gradebook_entry_reference': 'gradebookEntryReference',
        'student_reference': 'studentReference',
        'assignment_late_status_descriptor': 'assignmentLateStatusDescriptor',
        'competency_level_descriptor': 'competencyLevelDescriptor',
        'date_fulfilled': 'dateFulfilled',
        'diagnostic_statement': 'diagnosticStatement',
        'letter_grade_earned': 'letterGradeEarned',
        'numeric_grade_earned': 'numericGradeEarned',
        'points_earned': 'pointsEarned',
        'submission_status_descriptor': 'submissionStatusDescriptor',
        'time_fulfilled': 'timeFulfilled',
        'etag': '_etag'
    }

    def __init__(self, id=None, gradebook_entry_reference=None, student_reference=None, assignment_late_status_descriptor=None, competency_level_descriptor=None, date_fulfilled=None, diagnostic_statement=None, letter_grade_earned=None, numeric_grade_earned=None, points_earned=None, submission_status_descriptor=None, time_fulfilled=None, etag=None, _configuration=None):  # noqa: E501
        """EdFiStudentGradebookEntry - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._gradebook_entry_reference = None
        self._student_reference = None
        self._assignment_late_status_descriptor = None
        self._competency_level_descriptor = None
        self._date_fulfilled = None
        self._diagnostic_statement = None
        self._letter_grade_earned = None
        self._numeric_grade_earned = None
        self._points_earned = None
        self._submission_status_descriptor = None
        self._time_fulfilled = None
        self._etag = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.gradebook_entry_reference = gradebook_entry_reference
        self.student_reference = student_reference
        if assignment_late_status_descriptor is not None:
            self.assignment_late_status_descriptor = assignment_late_status_descriptor
        if competency_level_descriptor is not None:
            self.competency_level_descriptor = competency_level_descriptor
        if date_fulfilled is not None:
            self.date_fulfilled = date_fulfilled
        if diagnostic_statement is not None:
            self.diagnostic_statement = diagnostic_statement
        if letter_grade_earned is not None:
            self.letter_grade_earned = letter_grade_earned
        if numeric_grade_earned is not None:
            self.numeric_grade_earned = numeric_grade_earned
        if points_earned is not None:
            self.points_earned = points_earned
        if submission_status_descriptor is not None:
            self.submission_status_descriptor = submission_status_descriptor
        if time_fulfilled is not None:
            self.time_fulfilled = time_fulfilled
        if etag is not None:
            self.etag = etag

    @property
    def id(self):
        """Gets the id of this EdFiStudentGradebookEntry.  # noqa: E501

          # noqa: E501

        :return: The id of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EdFiStudentGradebookEntry.

          # noqa: E501

        :param id: The id of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def gradebook_entry_reference(self):
        """Gets the gradebook_entry_reference of this EdFiStudentGradebookEntry.  # noqa: E501


        :return: The gradebook_entry_reference of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: EdFiGradebookEntryReference
        """
        return self._gradebook_entry_reference

    @gradebook_entry_reference.setter
    def gradebook_entry_reference(self, gradebook_entry_reference):
        """Sets the gradebook_entry_reference of this EdFiStudentGradebookEntry.


        :param gradebook_entry_reference: The gradebook_entry_reference of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: EdFiGradebookEntryReference
        """
        if self._configuration.client_side_validation and gradebook_entry_reference is None:
            raise ValueError("Invalid value for `gradebook_entry_reference`, must not be `None`")  # noqa: E501

        self._gradebook_entry_reference = gradebook_entry_reference

    @property
    def student_reference(self):
        """Gets the student_reference of this EdFiStudentGradebookEntry.  # noqa: E501


        :return: The student_reference of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: EdFiStudentReference
        """
        return self._student_reference

    @student_reference.setter
    def student_reference(self, student_reference):
        """Sets the student_reference of this EdFiStudentGradebookEntry.


        :param student_reference: The student_reference of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: EdFiStudentReference
        """
        if self._configuration.client_side_validation and student_reference is None:
            raise ValueError("Invalid value for `student_reference`, must not be `None`")  # noqa: E501

        self._student_reference = student_reference

    @property
    def assignment_late_status_descriptor(self):
        """Gets the assignment_late_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501

        Status of whether the assignment was submitted after the due date and/or marked as.  # noqa: E501

        :return: The assignment_late_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._assignment_late_status_descriptor

    @assignment_late_status_descriptor.setter
    def assignment_late_status_descriptor(self, assignment_late_status_descriptor):
        """Sets the assignment_late_status_descriptor of this EdFiStudentGradebookEntry.

        Status of whether the assignment was submitted after the due date and/or marked as.  # noqa: E501

        :param assignment_late_status_descriptor: The assignment_late_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                assignment_late_status_descriptor is not None and len(assignment_late_status_descriptor) > 306):
            raise ValueError("Invalid value for `assignment_late_status_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._assignment_late_status_descriptor = assignment_late_status_descriptor

    @property
    def competency_level_descriptor(self):
        """Gets the competency_level_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501

        The competency level assessed for the student for the referenced learning objective.  # noqa: E501

        :return: The competency_level_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._competency_level_descriptor

    @competency_level_descriptor.setter
    def competency_level_descriptor(self, competency_level_descriptor):
        """Sets the competency_level_descriptor of this EdFiStudentGradebookEntry.

        The competency level assessed for the student for the referenced learning objective.  # noqa: E501

        :param competency_level_descriptor: The competency_level_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                competency_level_descriptor is not None and len(competency_level_descriptor) > 306):
            raise ValueError("Invalid value for `competency_level_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._competency_level_descriptor = competency_level_descriptor

    @property
    def date_fulfilled(self):
        """Gets the date_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501

        The date an assignment was turned in or the date of an assessment.  # noqa: E501

        :return: The date_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: date
        """
        return self._date_fulfilled

    @date_fulfilled.setter
    def date_fulfilled(self, date_fulfilled):
        """Sets the date_fulfilled of this EdFiStudentGradebookEntry.

        The date an assignment was turned in or the date of an assessment.  # noqa: E501

        :param date_fulfilled: The date_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: date
        """

        self._date_fulfilled = date_fulfilled

    @property
    def diagnostic_statement(self):
        """Gets the diagnostic_statement of this EdFiStudentGradebookEntry.  # noqa: E501

        A statement provided by the teacher that provides information in addition to the grade or assessment score.  # noqa: E501

        :return: The diagnostic_statement of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._diagnostic_statement

    @diagnostic_statement.setter
    def diagnostic_statement(self, diagnostic_statement):
        """Sets the diagnostic_statement of this EdFiStudentGradebookEntry.

        A statement provided by the teacher that provides information in addition to the grade or assessment score.  # noqa: E501

        :param diagnostic_statement: The diagnostic_statement of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                diagnostic_statement is not None and len(diagnostic_statement) > 1024):
            raise ValueError("Invalid value for `diagnostic_statement`, length must be less than or equal to `1024`")  # noqa: E501

        self._diagnostic_statement = diagnostic_statement

    @property
    def letter_grade_earned(self):
        """Gets the letter_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501

        A final or interim (grading period) indicator of student performance in a class as submitted by the instructor.  # noqa: E501

        :return: The letter_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._letter_grade_earned

    @letter_grade_earned.setter
    def letter_grade_earned(self, letter_grade_earned):
        """Sets the letter_grade_earned of this EdFiStudentGradebookEntry.

        A final or interim (grading period) indicator of student performance in a class as submitted by the instructor.  # noqa: E501

        :param letter_grade_earned: The letter_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                letter_grade_earned is not None and len(letter_grade_earned) > 20):
            raise ValueError("Invalid value for `letter_grade_earned`, length must be less than or equal to `20`")  # noqa: E501

        self._letter_grade_earned = letter_grade_earned

    @property
    def numeric_grade_earned(self):
        """Gets the numeric_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501

        A final or interim (grading period) indicator of student performance in a class as submitted by the instructor.  # noqa: E501

        :return: The numeric_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: float
        """
        return self._numeric_grade_earned

    @numeric_grade_earned.setter
    def numeric_grade_earned(self, numeric_grade_earned):
        """Sets the numeric_grade_earned of this EdFiStudentGradebookEntry.

        A final or interim (grading period) indicator of student performance in a class as submitted by the instructor.  # noqa: E501

        :param numeric_grade_earned: The numeric_grade_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: float
        """

        self._numeric_grade_earned = numeric_grade_earned

    @property
    def points_earned(self):
        """Gets the points_earned of this EdFiStudentGradebookEntry.  # noqa: E501

        The points earned for the submission. With extra credit, the points earned may exceed the max points.  # noqa: E501

        :return: The points_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: float
        """
        return self._points_earned

    @points_earned.setter
    def points_earned(self, points_earned):
        """Sets the points_earned of this EdFiStudentGradebookEntry.

        The points earned for the submission. With extra credit, the points earned may exceed the max points.  # noqa: E501

        :param points_earned: The points_earned of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: float
        """

        self._points_earned = points_earned

    @property
    def submission_status_descriptor(self):
        """Gets the submission_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501

        The status of the student's submission.  # noqa: E501

        :return: The submission_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._submission_status_descriptor

    @submission_status_descriptor.setter
    def submission_status_descriptor(self, submission_status_descriptor):
        """Sets the submission_status_descriptor of this EdFiStudentGradebookEntry.

        The status of the student's submission.  # noqa: E501

        :param submission_status_descriptor: The submission_status_descriptor of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                submission_status_descriptor is not None and len(submission_status_descriptor) > 306):
            raise ValueError("Invalid value for `submission_status_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._submission_status_descriptor = submission_status_descriptor

    @property
    def time_fulfilled(self):
        """Gets the time_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501

        The time an assignment was turned in on the date fulfilled.  # noqa: E501

        :return: The time_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._time_fulfilled

    @time_fulfilled.setter
    def time_fulfilled(self, time_fulfilled):
        """Sets the time_fulfilled of this EdFiStudentGradebookEntry.

        The time an assignment was turned in on the date fulfilled.  # noqa: E501

        :param time_fulfilled: The time_fulfilled of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """

        self._time_fulfilled = time_fulfilled

    @property
    def etag(self):
        """Gets the etag of this EdFiStudentGradebookEntry.  # noqa: E501

        A unique system-generated value that identifies the version of the resource.  # noqa: E501

        :return: The etag of this EdFiStudentGradebookEntry.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this EdFiStudentGradebookEntry.

        A unique system-generated value that identifies the version of the resource.  # noqa: E501

        :param etag: The etag of this EdFiStudentGradebookEntry.  # noqa: E501
        :type: str
        """

        self._etag = etag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdFiStudentGradebookEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdFiStudentGradebookEntry):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EdFiStudentGradebookEntry):
            return True

        return self.to_dict() != other.to_dict()
