# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiAccountabilityRatingKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rating_title': 'str',
        'education_organization_id': 'int',
        'school_year': 'int'
    }

    attribute_map = {
        'rating_title': 'ratingTitle',
        'education_organization_id': 'educationOrganizationId',
        'school_year': 'schoolYear'
    }

    def __init__(self, rating_title=None, education_organization_id=None, school_year=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiAccountabilityRatingKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._rating_title = None
        self._education_organization_id = None
        self._school_year = None
        self.discriminator = None

        if rating_title is not None:
            self.rating_title = rating_title
        if education_organization_id is not None:
            self.education_organization_id = education_organization_id
        if school_year is not None:
            self.school_year = school_year

    @property
    def rating_title(self):
        """Gets the rating_title of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501

        The title of the rating.  # noqa: E501

        :return: The rating_title of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :rtype: str
        """
        return self._rating_title

    @rating_title.setter
    def rating_title(self, rating_title):
        """Sets the rating_title of this TrackedChangesEdFiAccountabilityRatingKey.

        The title of the rating.  # noqa: E501

        :param rating_title: The rating_title of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                rating_title is not None and len(rating_title) > 60):
            raise ValueError("Invalid value for `rating_title`, length must be less than or equal to `60`")  # noqa: E501

        self._rating_title = rating_title

    @property
    def education_organization_id(self):
        """Gets the education_organization_id of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The education_organization_id of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :rtype: int
        """
        return self._education_organization_id

    @education_organization_id.setter
    def education_organization_id(self, education_organization_id):
        """Sets the education_organization_id of this TrackedChangesEdFiAccountabilityRatingKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param education_organization_id: The education_organization_id of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :type: int
        """

        self._education_organization_id = education_organization_id

    @property
    def school_year(self):
        """Gets the school_year of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501

        The school year for which the accountability rating is assessed.  # noqa: E501

        :return: The school_year of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :rtype: int
        """
        return self._school_year

    @school_year.setter
    def school_year(self, school_year):
        """Sets the school_year of this TrackedChangesEdFiAccountabilityRatingKey.

        The school year for which the accountability rating is assessed.  # noqa: E501

        :param school_year: The school_year of this TrackedChangesEdFiAccountabilityRatingKey.  # noqa: E501
        :type: int
        """

        self._school_year = school_year

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiAccountabilityRatingKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiAccountabilityRatingKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiAccountabilityRatingKey):
            return True

        return self.to_dict() != other.to_dict()
