# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiCompetencyObjectiveKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objective_grade_level_descriptor': 'str',
        'objective': 'str',
        'education_organization_id': 'int'
    }

    attribute_map = {
        'objective_grade_level_descriptor': 'objectiveGradeLevelDescriptor',
        'objective': 'objective',
        'education_organization_id': 'educationOrganizationId'
    }

    def __init__(self, objective_grade_level_descriptor=None, objective=None, education_organization_id=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiCompetencyObjectiveKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._objective_grade_level_descriptor = None
        self._objective = None
        self._education_organization_id = None
        self.discriminator = None

        if objective_grade_level_descriptor is not None:
            self.objective_grade_level_descriptor = objective_grade_level_descriptor
        if objective is not None:
            self.objective = objective
        if education_organization_id is not None:
            self.education_organization_id = education_organization_id

    @property
    def objective_grade_level_descriptor(self):
        """Gets the objective_grade_level_descriptor of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501

        The grade level for which the competency objective is targeted.  # noqa: E501

        :return: The objective_grade_level_descriptor of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._objective_grade_level_descriptor

    @objective_grade_level_descriptor.setter
    def objective_grade_level_descriptor(self, objective_grade_level_descriptor):
        """Sets the objective_grade_level_descriptor of this TrackedChangesEdFiCompetencyObjectiveKey.

        The grade level for which the competency objective is targeted.  # noqa: E501

        :param objective_grade_level_descriptor: The objective_grade_level_descriptor of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                objective_grade_level_descriptor is not None and len(objective_grade_level_descriptor) > 306):
            raise ValueError("Invalid value for `objective_grade_level_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._objective_grade_level_descriptor = objective_grade_level_descriptor

    @property
    def objective(self):
        """Gets the objective of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501

        The designated title of the competency objective.  # noqa: E501

        :return: The objective of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._objective

    @objective.setter
    def objective(self, objective):
        """Sets the objective of this TrackedChangesEdFiCompetencyObjectiveKey.

        The designated title of the competency objective.  # noqa: E501

        :param objective: The objective of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                objective is not None and len(objective) > 60):
            raise ValueError("Invalid value for `objective`, length must be less than or equal to `60`")  # noqa: E501

        self._objective = objective

    @property
    def education_organization_id(self):
        """Gets the education_organization_id of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The education_organization_id of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._education_organization_id

    @education_organization_id.setter
    def education_organization_id(self, education_organization_id):
        """Sets the education_organization_id of this TrackedChangesEdFiCompetencyObjectiveKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param education_organization_id: The education_organization_id of this TrackedChangesEdFiCompetencyObjectiveKey.  # noqa: E501
        :type: int
        """

        self._education_organization_id = education_organization_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiCompetencyObjectiveKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiCompetencyObjectiveKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiCompetencyObjectiveKey):
            return True

        return self.to_dict() != other.to_dict()
