# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiCourseTranscriptKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'course_attempt_result_descriptor': 'str',
        'course_code': 'str',
        'course_education_organization_id': 'int',
        'education_organization_id': 'int',
        'school_year': 'int',
        'student_unique_id': 'str',
        'term_descriptor': 'str'
    }

    attribute_map = {
        'course_attempt_result_descriptor': 'courseAttemptResultDescriptor',
        'course_code': 'courseCode',
        'course_education_organization_id': 'courseEducationOrganizationId',
        'education_organization_id': 'educationOrganizationId',
        'school_year': 'schoolYear',
        'student_unique_id': 'studentUniqueId',
        'term_descriptor': 'termDescriptor'
    }

    def __init__(self, course_attempt_result_descriptor=None, course_code=None, course_education_organization_id=None, education_organization_id=None, school_year=None, student_unique_id=None, term_descriptor=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiCourseTranscriptKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._course_attempt_result_descriptor = None
        self._course_code = None
        self._course_education_organization_id = None
        self._education_organization_id = None
        self._school_year = None
        self._student_unique_id = None
        self._term_descriptor = None
        self.discriminator = None

        if course_attempt_result_descriptor is not None:
            self.course_attempt_result_descriptor = course_attempt_result_descriptor
        if course_code is not None:
            self.course_code = course_code
        if course_education_organization_id is not None:
            self.course_education_organization_id = course_education_organization_id
        if education_organization_id is not None:
            self.education_organization_id = education_organization_id
        if school_year is not None:
            self.school_year = school_year
        if student_unique_id is not None:
            self.student_unique_id = student_unique_id
        if term_descriptor is not None:
            self.term_descriptor = term_descriptor

    @property
    def course_attempt_result_descriptor(self):
        """Gets the course_attempt_result_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        The result from the student's attempt to take the course.  # noqa: E501

        :return: The course_attempt_result_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: str
        """
        return self._course_attempt_result_descriptor

    @course_attempt_result_descriptor.setter
    def course_attempt_result_descriptor(self, course_attempt_result_descriptor):
        """Sets the course_attempt_result_descriptor of this TrackedChangesEdFiCourseTranscriptKey.

        The result from the student's attempt to take the course.  # noqa: E501

        :param course_attempt_result_descriptor: The course_attempt_result_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                course_attempt_result_descriptor is not None and len(course_attempt_result_descriptor) > 306):
            raise ValueError("Invalid value for `course_attempt_result_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._course_attempt_result_descriptor = course_attempt_result_descriptor

    @property
    def course_code(self):
        """Gets the course_code of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        A unique alphanumeric code assigned to a course.  # noqa: E501

        :return: The course_code of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: str
        """
        return self._course_code

    @course_code.setter
    def course_code(self, course_code):
        """Sets the course_code of this TrackedChangesEdFiCourseTranscriptKey.

        A unique alphanumeric code assigned to a course.  # noqa: E501

        :param course_code: The course_code of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                course_code is not None and len(course_code) > 60):
            raise ValueError("Invalid value for `course_code`, length must be less than or equal to `60`")  # noqa: E501

        self._course_code = course_code

    @property
    def course_education_organization_id(self):
        """Gets the course_education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The course_education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: int
        """
        return self._course_education_organization_id

    @course_education_organization_id.setter
    def course_education_organization_id(self, course_education_organization_id):
        """Sets the course_education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param course_education_organization_id: The course_education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: int
        """

        self._course_education_organization_id = course_education_organization_id

    @property
    def education_organization_id(self):
        """Gets the education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: int
        """
        return self._education_organization_id

    @education_organization_id.setter
    def education_organization_id(self, education_organization_id):
        """Sets the education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param education_organization_id: The education_organization_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: int
        """

        self._education_organization_id = education_organization_id

    @property
    def school_year(self):
        """Gets the school_year of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        The identifier for the school year.  # noqa: E501

        :return: The school_year of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: int
        """
        return self._school_year

    @school_year.setter
    def school_year(self, school_year):
        """Sets the school_year of this TrackedChangesEdFiCourseTranscriptKey.

        The identifier for the school year.  # noqa: E501

        :param school_year: The school_year of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: int
        """

        self._school_year = school_year

    @property
    def student_unique_id(self):
        """Gets the student_unique_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :return: The student_unique_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: str
        """
        return self._student_unique_id

    @student_unique_id.setter
    def student_unique_id(self, student_unique_id):
        """Sets the student_unique_id of this TrackedChangesEdFiCourseTranscriptKey.

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :param student_unique_id: The student_unique_id of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                student_unique_id is not None and len(student_unique_id) > 32):
            raise ValueError("Invalid value for `student_unique_id`, length must be less than or equal to `32`")  # noqa: E501

        self._student_unique_id = student_unique_id

    @property
    def term_descriptor(self):
        """Gets the term_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501

        The term for the session during the school year.  # noqa: E501

        :return: The term_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :rtype: str
        """
        return self._term_descriptor

    @term_descriptor.setter
    def term_descriptor(self, term_descriptor):
        """Sets the term_descriptor of this TrackedChangesEdFiCourseTranscriptKey.

        The term for the session during the school year.  # noqa: E501

        :param term_descriptor: The term_descriptor of this TrackedChangesEdFiCourseTranscriptKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                term_descriptor is not None and len(term_descriptor) > 306):
            raise ValueError("Invalid value for `term_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._term_descriptor = term_descriptor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiCourseTranscriptKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiCourseTranscriptKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiCourseTranscriptKey):
            return True

        return self.to_dict() != other.to_dict()
