# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiSurveyProgramAssociationKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'education_organization_id': 'int',
        'program_name': 'str',
        'program_type_descriptor': 'str',
        'namespace': 'str',
        'survey_identifier': 'str'
    }

    attribute_map = {
        'education_organization_id': 'educationOrganizationId',
        'program_name': 'programName',
        'program_type_descriptor': 'programTypeDescriptor',
        'namespace': 'namespace',
        'survey_identifier': 'surveyIdentifier'
    }

    def __init__(self, education_organization_id=None, program_name=None, program_type_descriptor=None, namespace=None, survey_identifier=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiSurveyProgramAssociationKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._education_organization_id = None
        self._program_name = None
        self._program_type_descriptor = None
        self._namespace = None
        self._survey_identifier = None
        self.discriminator = None

        if education_organization_id is not None:
            self.education_organization_id = education_organization_id
        if program_name is not None:
            self.program_name = program_name
        if program_type_descriptor is not None:
            self.program_type_descriptor = program_type_descriptor
        if namespace is not None:
            self.namespace = namespace
        if survey_identifier is not None:
            self.survey_identifier = survey_identifier

    @property
    def education_organization_id(self):
        """Gets the education_organization_id of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The education_organization_id of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :rtype: int
        """
        return self._education_organization_id

    @education_organization_id.setter
    def education_organization_id(self, education_organization_id):
        """Sets the education_organization_id of this TrackedChangesEdFiSurveyProgramAssociationKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param education_organization_id: The education_organization_id of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :type: int
        """

        self._education_organization_id = education_organization_id

    @property
    def program_name(self):
        """Gets the program_name of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501

        The formal name of the program of instruction, training, services, or benefits available through federal, state, or local agencies.  # noqa: E501

        :return: The program_name of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :rtype: str
        """
        return self._program_name

    @program_name.setter
    def program_name(self, program_name):
        """Sets the program_name of this TrackedChangesEdFiSurveyProgramAssociationKey.

        The formal name of the program of instruction, training, services, or benefits available through federal, state, or local agencies.  # noqa: E501

        :param program_name: The program_name of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                program_name is not None and len(program_name) > 60):
            raise ValueError("Invalid value for `program_name`, length must be less than or equal to `60`")  # noqa: E501

        self._program_name = program_name

    @property
    def program_type_descriptor(self):
        """Gets the program_type_descriptor of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501

        The type of program.  # noqa: E501

        :return: The program_type_descriptor of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :rtype: str
        """
        return self._program_type_descriptor

    @program_type_descriptor.setter
    def program_type_descriptor(self, program_type_descriptor):
        """Sets the program_type_descriptor of this TrackedChangesEdFiSurveyProgramAssociationKey.

        The type of program.  # noqa: E501

        :param program_type_descriptor: The program_type_descriptor of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                program_type_descriptor is not None and len(program_type_descriptor) > 306):
            raise ValueError("Invalid value for `program_type_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._program_type_descriptor = program_type_descriptor

    @property
    def namespace(self):
        """Gets the namespace of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501

        Namespace for the survey.  # noqa: E501

        :return: The namespace of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this TrackedChangesEdFiSurveyProgramAssociationKey.

        Namespace for the survey.  # noqa: E501

        :param namespace: The namespace of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                namespace is not None and len(namespace) > 255):
            raise ValueError("Invalid value for `namespace`, length must be less than or equal to `255`")  # noqa: E501

        self._namespace = namespace

    @property
    def survey_identifier(self):
        """Gets the survey_identifier of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501

        The unique survey identifier from the survey tool.  # noqa: E501

        :return: The survey_identifier of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :rtype: str
        """
        return self._survey_identifier

    @survey_identifier.setter
    def survey_identifier(self, survey_identifier):
        """Sets the survey_identifier of this TrackedChangesEdFiSurveyProgramAssociationKey.

        The unique survey identifier from the survey tool.  # noqa: E501

        :param survey_identifier: The survey_identifier of this TrackedChangesEdFiSurveyProgramAssociationKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                survey_identifier is not None and len(survey_identifier) > 60):
            raise ValueError("Invalid value for `survey_identifier`, length must be less than or equal to `60`")  # noqa: E501

        self._survey_identifier = survey_identifier

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiSurveyProgramAssociationKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiSurveyProgramAssociationKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiSurveyProgramAssociationKey):
            return True

        return self.to_dict() != other.to_dict()
