# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiStudentLearningObjectiveKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grading_period_descriptor': 'str',
        'grading_period_sequence': 'int',
        'grading_period_school_id': 'int',
        'grading_period_school_year': 'int',
        'learning_objective_id': 'str',
        'namespace': 'str',
        'student_unique_id': 'str'
    }

    attribute_map = {
        'grading_period_descriptor': 'gradingPeriodDescriptor',
        'grading_period_sequence': 'gradingPeriodSequence',
        'grading_period_school_id': 'gradingPeriodSchoolId',
        'grading_period_school_year': 'gradingPeriodSchoolYear',
        'learning_objective_id': 'learningObjectiveId',
        'namespace': 'namespace',
        'student_unique_id': 'studentUniqueId'
    }

    def __init__(self, grading_period_descriptor=None, grading_period_sequence=None, grading_period_school_id=None, grading_period_school_year=None, learning_objective_id=None, namespace=None, student_unique_id=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiStudentLearningObjectiveKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._grading_period_descriptor = None
        self._grading_period_sequence = None
        self._grading_period_school_id = None
        self._grading_period_school_year = None
        self._learning_objective_id = None
        self._namespace = None
        self._student_unique_id = None
        self.discriminator = None

        if grading_period_descriptor is not None:
            self.grading_period_descriptor = grading_period_descriptor
        if grading_period_sequence is not None:
            self.grading_period_sequence = grading_period_sequence
        if grading_period_school_id is not None:
            self.grading_period_school_id = grading_period_school_id
        if grading_period_school_year is not None:
            self.grading_period_school_year = grading_period_school_year
        if learning_objective_id is not None:
            self.learning_objective_id = learning_objective_id
        if namespace is not None:
            self.namespace = namespace
        if student_unique_id is not None:
            self.student_unique_id = student_unique_id

    @property
    def grading_period_descriptor(self):
        """Gets the grading_period_descriptor of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        The name of the period for which grades are reported.  # noqa: E501

        :return: The grading_period_descriptor of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._grading_period_descriptor

    @grading_period_descriptor.setter
    def grading_period_descriptor(self, grading_period_descriptor):
        """Sets the grading_period_descriptor of this TrackedChangesEdFiStudentLearningObjectiveKey.

        The name of the period for which grades are reported.  # noqa: E501

        :param grading_period_descriptor: The grading_period_descriptor of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                grading_period_descriptor is not None and len(grading_period_descriptor) > 306):
            raise ValueError("Invalid value for `grading_period_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._grading_period_descriptor = grading_period_descriptor

    @property
    def grading_period_sequence(self):
        """Gets the grading_period_sequence of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        The sequential order of this period relative to other periods.  # noqa: E501

        :return: The grading_period_sequence of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_sequence

    @grading_period_sequence.setter
    def grading_period_sequence(self, grading_period_sequence):
        """Sets the grading_period_sequence of this TrackedChangesEdFiStudentLearningObjectiveKey.

        The sequential order of this period relative to other periods.  # noqa: E501

        :param grading_period_sequence: The grading_period_sequence of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_sequence = grading_period_sequence

    @property
    def grading_period_school_id(self):
        """Gets the grading_period_school_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        The identifier assigned to a school.  # noqa: E501

        :return: The grading_period_school_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_school_id

    @grading_period_school_id.setter
    def grading_period_school_id(self, grading_period_school_id):
        """Sets the grading_period_school_id of this TrackedChangesEdFiStudentLearningObjectiveKey.

        The identifier assigned to a school.  # noqa: E501

        :param grading_period_school_id: The grading_period_school_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_school_id = grading_period_school_id

    @property
    def grading_period_school_year(self):
        """Gets the grading_period_school_year of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        The identifier for the grading period school year.  # noqa: E501

        :return: The grading_period_school_year of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_school_year

    @grading_period_school_year.setter
    def grading_period_school_year(self, grading_period_school_year):
        """Sets the grading_period_school_year of this TrackedChangesEdFiStudentLearningObjectiveKey.

        The identifier for the grading period school year.  # noqa: E501

        :param grading_period_school_year: The grading_period_school_year of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_school_year = grading_period_school_year

    @property
    def learning_objective_id(self):
        """Gets the learning_objective_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        The identifier for the specific learning objective in the context of a standard (e.g., 111.15.3.1.A).  # noqa: E501

        :return: The learning_objective_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._learning_objective_id

    @learning_objective_id.setter
    def learning_objective_id(self, learning_objective_id):
        """Sets the learning_objective_id of this TrackedChangesEdFiStudentLearningObjectiveKey.

        The identifier for the specific learning objective in the context of a standard (e.g., 111.15.3.1.A).  # noqa: E501

        :param learning_objective_id: The learning_objective_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                learning_objective_id is not None and len(learning_objective_id) > 60):
            raise ValueError("Invalid value for `learning_objective_id`, length must be less than or equal to `60`")  # noqa: E501

        self._learning_objective_id = learning_objective_id

    @property
    def namespace(self):
        """Gets the namespace of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        Namespace for the learning objective.  # noqa: E501

        :return: The namespace of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this TrackedChangesEdFiStudentLearningObjectiveKey.

        Namespace for the learning objective.  # noqa: E501

        :param namespace: The namespace of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                namespace is not None and len(namespace) > 255):
            raise ValueError("Invalid value for `namespace`, length must be less than or equal to `255`")  # noqa: E501

        self._namespace = namespace

    @property
    def student_unique_id(self):
        """Gets the student_unique_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :return: The student_unique_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._student_unique_id

    @student_unique_id.setter
    def student_unique_id(self, student_unique_id):
        """Sets the student_unique_id of this TrackedChangesEdFiStudentLearningObjectiveKey.

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :param student_unique_id: The student_unique_id of this TrackedChangesEdFiStudentLearningObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                student_unique_id is not None and len(student_unique_id) > 32):
            raise ValueError("Invalid value for `student_unique_id`, length must be less than or equal to `32`")  # noqa: E501

        self._student_unique_id = student_unique_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiStudentLearningObjectiveKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiStudentLearningObjectiveKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiStudentLearningObjectiveKey):
            return True

        return self.to_dict() != other.to_dict()
