# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TrackedChangesEdFiStudentCompetencyObjectiveKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objective_education_organization_id': 'int',
        'objective': 'str',
        'objective_grade_level_descriptor': 'str',
        'grading_period_descriptor': 'str',
        'grading_period_sequence': 'int',
        'grading_period_school_id': 'int',
        'grading_period_school_year': 'int',
        'student_unique_id': 'str'
    }

    attribute_map = {
        'objective_education_organization_id': 'objectiveEducationOrganizationId',
        'objective': 'objective',
        'objective_grade_level_descriptor': 'objectiveGradeLevelDescriptor',
        'grading_period_descriptor': 'gradingPeriodDescriptor',
        'grading_period_sequence': 'gradingPeriodSequence',
        'grading_period_school_id': 'gradingPeriodSchoolId',
        'grading_period_school_year': 'gradingPeriodSchoolYear',
        'student_unique_id': 'studentUniqueId'
    }

    def __init__(self, objective_education_organization_id=None, objective=None, objective_grade_level_descriptor=None, grading_period_descriptor=None, grading_period_sequence=None, grading_period_school_id=None, grading_period_school_year=None, student_unique_id=None, _configuration=None):  # noqa: E501
        """TrackedChangesEdFiStudentCompetencyObjectiveKey - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._objective_education_organization_id = None
        self._objective = None
        self._objective_grade_level_descriptor = None
        self._grading_period_descriptor = None
        self._grading_period_sequence = None
        self._grading_period_school_id = None
        self._grading_period_school_year = None
        self._student_unique_id = None
        self.discriminator = None

        if objective_education_organization_id is not None:
            self.objective_education_organization_id = objective_education_organization_id
        if objective is not None:
            self.objective = objective
        if objective_grade_level_descriptor is not None:
            self.objective_grade_level_descriptor = objective_grade_level_descriptor
        if grading_period_descriptor is not None:
            self.grading_period_descriptor = grading_period_descriptor
        if grading_period_sequence is not None:
            self.grading_period_sequence = grading_period_sequence
        if grading_period_school_id is not None:
            self.grading_period_school_id = grading_period_school_id
        if grading_period_school_year is not None:
            self.grading_period_school_year = grading_period_school_year
        if student_unique_id is not None:
            self.student_unique_id = student_unique_id

    @property
    def objective_education_organization_id(self):
        """Gets the objective_education_organization_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The identifier assigned to an education organization.  # noqa: E501

        :return: The objective_education_organization_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._objective_education_organization_id

    @objective_education_organization_id.setter
    def objective_education_organization_id(self, objective_education_organization_id):
        """Sets the objective_education_organization_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The identifier assigned to an education organization.  # noqa: E501

        :param objective_education_organization_id: The objective_education_organization_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: int
        """

        self._objective_education_organization_id = objective_education_organization_id

    @property
    def objective(self):
        """Gets the objective of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The designated title of the competency objective.  # noqa: E501

        :return: The objective of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._objective

    @objective.setter
    def objective(self, objective):
        """Sets the objective of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The designated title of the competency objective.  # noqa: E501

        :param objective: The objective of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                objective is not None and len(objective) > 60):
            raise ValueError("Invalid value for `objective`, length must be less than or equal to `60`")  # noqa: E501

        self._objective = objective

    @property
    def objective_grade_level_descriptor(self):
        """Gets the objective_grade_level_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The grade level for which the competency objective is targeted.  # noqa: E501

        :return: The objective_grade_level_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._objective_grade_level_descriptor

    @objective_grade_level_descriptor.setter
    def objective_grade_level_descriptor(self, objective_grade_level_descriptor):
        """Sets the objective_grade_level_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The grade level for which the competency objective is targeted.  # noqa: E501

        :param objective_grade_level_descriptor: The objective_grade_level_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                objective_grade_level_descriptor is not None and len(objective_grade_level_descriptor) > 306):
            raise ValueError("Invalid value for `objective_grade_level_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._objective_grade_level_descriptor = objective_grade_level_descriptor

    @property
    def grading_period_descriptor(self):
        """Gets the grading_period_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The name of the period for which grades are reported.  # noqa: E501

        :return: The grading_period_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._grading_period_descriptor

    @grading_period_descriptor.setter
    def grading_period_descriptor(self, grading_period_descriptor):
        """Sets the grading_period_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The name of the period for which grades are reported.  # noqa: E501

        :param grading_period_descriptor: The grading_period_descriptor of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                grading_period_descriptor is not None and len(grading_period_descriptor) > 306):
            raise ValueError("Invalid value for `grading_period_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._grading_period_descriptor = grading_period_descriptor

    @property
    def grading_period_sequence(self):
        """Gets the grading_period_sequence of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The sequential order of this period relative to other periods.  # noqa: E501

        :return: The grading_period_sequence of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_sequence

    @grading_period_sequence.setter
    def grading_period_sequence(self, grading_period_sequence):
        """Sets the grading_period_sequence of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The sequential order of this period relative to other periods.  # noqa: E501

        :param grading_period_sequence: The grading_period_sequence of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_sequence = grading_period_sequence

    @property
    def grading_period_school_id(self):
        """Gets the grading_period_school_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The identifier assigned to a school.  # noqa: E501

        :return: The grading_period_school_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_school_id

    @grading_period_school_id.setter
    def grading_period_school_id(self, grading_period_school_id):
        """Sets the grading_period_school_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The identifier assigned to a school.  # noqa: E501

        :param grading_period_school_id: The grading_period_school_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_school_id = grading_period_school_id

    @property
    def grading_period_school_year(self):
        """Gets the grading_period_school_year of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        The identifier for the grading period school year.  # noqa: E501

        :return: The grading_period_school_year of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: int
        """
        return self._grading_period_school_year

    @grading_period_school_year.setter
    def grading_period_school_year(self, grading_period_school_year):
        """Sets the grading_period_school_year of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        The identifier for the grading period school year.  # noqa: E501

        :param grading_period_school_year: The grading_period_school_year of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: int
        """

        self._grading_period_school_year = grading_period_school_year

    @property
    def student_unique_id(self):
        """Gets the student_unique_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :return: The student_unique_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :rtype: str
        """
        return self._student_unique_id

    @student_unique_id.setter
    def student_unique_id(self, student_unique_id):
        """Sets the student_unique_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.

        A unique alphanumeric code assigned to a student.  # noqa: E501

        :param student_unique_id: The student_unique_id of this TrackedChangesEdFiStudentCompetencyObjectiveKey.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                student_unique_id is not None and len(student_unique_id) > 32):
            raise ValueError("Invalid value for `student_unique_id`, length must be less than or equal to `32`")  # noqa: E501

        self._student_unique_id = student_unique_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackedChangesEdFiStudentCompetencyObjectiveKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackedChangesEdFiStudentCompetencyObjectiveKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrackedChangesEdFiStudentCompetencyObjectiveKey):
            return True

        return self.to_dict() != other.to_dict()
